# Site settings
title: C.S. Rhymes
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  C.S. Rhymes author of How NOT to make a website and How NOT to use a smartphone
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://www.csrhymes.com # the base hostname & protocol for your site
twitter_username: chrisrhymes
github_username:  chrisrhymes
image: https://csrhymes.com/img/csrhymeslogo.png


remote_theme: chrisrhymes/bulma-clean-theme
#theme: bulma-clean-theme
google_analytics: UA-49024852-2
livereload: true

# Pagination settings
paginate: 5
paginate_path: "/blog/page:num"

# Build settings
markdown: kramdown

#Syntax Highlighter
highlighter: rouge

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-redirect-from
  - github-pages

sass:
  style: compressed

collections:
  stories:
    output: true
  products: 
    output: true
    layout: product
    show_sidebar: false

exclude: [node_modules, gulpfile.js, vendor]

footer_menu: footer_menu

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "C.S. Rhymes"
      layout: post
      hero_image: /img/blog-hero.jpg
      show_sidebar: true
  -
    scope:
      path: ""
      type: "stories"
    values:
      author: "C.S. Rhymes"
      layout: post
      hero_image: /img/stories.jpg
  

# SEO
author: 
  twitter: chrisrhymes
lang: en_GB
twitter:
  username: chrisrhymes
  card: summary_large_image
facebook:
  publisher: https://www.facebook.com/CS-Rhymes-1423568567916115
social:
  name: C.S. Rhymes
  links:
    - https://www.twitter.com/chrisrhymes
    - https://www.facebook.com/CS-Rhymes-1423568567916115
    - https://github.com/chrisrhymes

feed:
  collections:
    - stories